/* ============================================================
   Companio — shared runtime config
   ============================================================
   THIS IS THE ONLY FILE YOU EDIT WITH YOUR KEYS.
   Paste your Supabase project URL + anon (public) key below ONCE.
   Every page (dashboard, both portals, set-password) loads this file,
   so you never paste keys into the HTML again.

   · This file is NOT regenerated by builds — safe across re-deploys.
   · Use the anon / public key only (NEVER the service_role key here).
   · Leave both blank to run the dashboard on demo data (no login).
   ============================================================ */

// ----- EDIT THESE TWO LINES (once) -----
window.SUPABASE_URL      = "";   // e.g. https://bouyfsfcfjeordmaaaof.supabase.co
window.SUPABASE_ANON_KEY = "";   // your anon / public key (starts with eyJ...)
// ---------------------------------------

/* Back-compat: existing scripts read bare globals `SUPABASE_URL` /
   `SUPABASE_ANON_KEY` (via `typeof ... !== 'undefined'`). Because this file
   loads at top-level before supabase.js, these `var` declarations create
   those globals. Do not remove. */
var SUPABASE_URL = window.SUPABASE_URL;
var SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY;
